###


GET http://localhost:4000/


//****************************************POST****************************************

###

GET http://localhost:4000/post
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk
###

GET http://localhost:4000/post/62253a28d9208e0a9fa5035b
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk
###


POST http://localhost:4000/post
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk
Content-Type: application/json

{
        "description": "this is my test post",
        "profileId": "1234",
        "productName": "shirt",
        "sku": "abc",
        "size": "L",
        "company": "Zara",
        "price": "100",
        "color": "black",
        "categoryId": "1",
        "subCategoryId": "2",
        "date": "3/3/22",
        "link": "www.example.com",
        "sizeAdjustment": "4",
        "rating": "5",
        "picturesUrl": ["pic1", "pic2"],
        "likes": [],
        "comments": []
}

###
PATCH  http://localhost:4000/post/62253a28d9208e0a9fa5035b/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk
Content-Type: application/json

{
        "description": "this is my edited post",
        "profileId": "edited profileId",
        "productName": "edited productName",
        "sku": "edited sku",
        "size": "edited size",
        "company": "edited company",
        "price": "edited price",
        "color": "edited color",
        "categoryId": "edited categoryId",
        "subCategoryId": "edited subCategoryId",
        "date": "edited date",
        "link": "edited link",
        "sizeAdjustment": "edited sizeAdjustment",
        "rating": "edited rating",
        "picturesUrl": ["edited imgUrl1", "edited imgUrl2"],
        "likes": [],
        "comments": []
}
###
DELETE   http://localhost:4000/post/62253a28d9208e0a9fa5035b/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk


//****************************************USER****************************************

###

POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email" : "b@a.com",
    "password" : "12345",
    "type" : "client"
}

###


POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email" : "b@a.com",
    "password" : "12345",
    "type" : "client"
}

###

//TODO: logout not working.
# POST http://localhost:4000/auth/logout
# # Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjBkYTRhNDgxODMxNDZlZDdmOGUzMCIsImlhdCI6MTY0NjMyODU4OH0.WIVzzshuKMWLM8NNY-cvGtK76IFW98uAMyRBkXtSNIo
# Content-Type: application/json

# {
#     "email" : "b@a.com",
#     "password" : "12345",
#     "type" : "client"
# }

###

//TODO: refreshToken not working.

# GET http://localhost:4000/auth/refreshToken
# Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjBkNmQ1NWYwYmI4N2ViMjBmYzQ4NCIsImlhdCI6MTY0NjMyMDA0NiwiZXhwIjoxNjQ2NDA2NDQ2fQ.b2YFf_4hBwszH07Qb-L20Fov_XYPC_POhgr9Bf4wl9g


//****************************************Profile****************************************

###

POST http://localhost:4000/profile
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjBkYTRhNDgxODMxNDZlZDdmOGUzMCIsImlhdCI6MTY0NjY0NTUxMCwiZXhwIjoxNjQ2NzMxOTEwfQ.KZL_t3cL-uWeVJe-_s-a-bFg6PMiQDPu_5K0iNzzf-w
Content-Type: application/json

{
        "userId": "1234",
        "firstName": "Yuval",
        "lastName": "Levi",
        "gender": "female",
        "userName": "yuv92",
        "birthday": "07.11.92",
        "pictureUrl": "pic1",
        "shoulder": "80",
        "chest": "80",
        "basin": "80",
        "waist": "80",
        "foot": "80",
        "height": "80",
        "weight": "80",
        "bodyType": "1",
        "status": false,
        "similarProfileId": [],
        "followers": [],
        "trackers": [],
        "notifications": [],
        "wishlist": [],
        "myPostsListId": []
}

###

GET http://localhost:4000/profile/6225d122b4e3e4eeb42151c3
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk

