###
GET http://localhost:4000/

//****************************************POST****************************************

###
GET http://localhost:4000/post
# Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk

###
GET http://localhost:4000/post/6228e49f73d4b8b300af9124
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjQ4MmQ0MDA5NmQ5OTUzOGYwZjBhMyIsImlhdCI6MTY0NzI2NDU5NywiZXhwIjoxNjQ3MzUwOTk3fQ.SmAGA85dK-OdKZpTy6el3zPjgka_8YtskHckPDwA6zg

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjQ4MmQ0MDA5NmQ5OTUzOGYwZjBhMyIsImlhdCI6MTY0NzI2NDE4MH0.pHxfvF60CAMsPBrVCPoX67GrIgDjqmC7WxwEylloF7w
###
POST http://localhost:4000/post
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjBkYTRhNDgxODMxNDZlZDdmOGUzMCIsImlhdCI6MTY0NzAwMTcxNCwiZXhwIjoxNjQ3MDg4MTE0fQ.G6Mf9Pvi6f2SBezY__zZ5VzzDnoreviqMldsyQ7u4zk
Content-Type: application/json

{
        "description": "this is my test post",
        "profileId": "1234",
        "productName": "shirt",
        "sku": "abc",
        "size": "L",
        "company": "Zara",
        "price": "100",
        "color": "black",
        "categoryId": "1",
        "subCategoryId": "2",
        "date": "3/3/22",
        "link": "www.example.com",
        "sizeAdjustment": "4",
        "rating": "5",
        "picturesUrl": ["pic1", "pic2"],
        "likes": [],
        "comments": []
}

###
PATCH  http://localhost:4000/post/622a6ec75afdc688ae7036f3/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0Njk0NzkzOSwiZXhwIjoxNjQ3MDM0MzM5fQ._9dREYzI8JAznD6ShMrWCIhEfHm0f29x7ya_qwuGyoE
Content-Type: application/json

{
        "description": "this is my edited post",
        "profileId": "edited profileId",
        "productName": "edited productName",
        "sku": "edited sku",
        "size": "edited size",
        "company": "edited company",
        "price": "edited price",
        "color": "edited color",
        "categoryId": "edited categoryId",
        "subCategoryId": "edited subCategoryId",
        "date": "edited date",
        "link": "edited link",
        "sizeAdjustment": "edited sizeAdjustment",
        "rating": "edited rating",
        "picturesUrl": ["edited imgUrl1", "edited imgUrl2"],
        "likes": [],
        "comments": ["6221e1328c6617aec927afb3"]
}
###
DELETE   http://localhost:4000/post/622a6ec75afdc688ae7036f3/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk


//****************************************USER****************************************

###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email" : "1",
    "password" : "1",
    "type" : "client"
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email" : "b@a.com",
    "password" : "12345",
    "type" : "client"
}

### 

GET http://localhost:4000/auth/getUser/1

###

//TODO: logout not working.
# POST http://localhost:4000/auth/logout
# # Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjBkYTRhNDgxODMxNDZlZDdmOGUzMCIsImlhdCI6MTY0NjMyODU4OH0.WIVzzshuKMWLM8NNY-cvGtK76IFW98uAMyRBkXtSNIo
# Content-Type: application/json

# {
#     "email" : "b@a.com",
#     "password" : "12345",
#     "type" : "client"
# }

###

//TODO: refreshToken not working.

# GET http://localhost:4000/auth/refreshToken
# Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjBkNmQ1NWYwYmI4N2ViMjBmYzQ4NCIsImlhdCI6MTY0NjMyMDA0NiwiZXhwIjoxNjQ2NDA2NDQ2fQ.b2YFf_4hBwszH07Qb-L20Fov_XYPC_POhgr9Bf4wl9g


//****************************************Profile****************************************

### 

GET http://localhost:4000/profile/getProfile/1/lilach

###
POST http://localhost:4000/profile
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjQ4MmQ0MDA5NmQ5OTUzOGYwZjBhMyIsImlhdCI6MTY0NzA5MTEzNywiZXhwIjoxNjQ3MTc3NTM3fQ.Q_qqv71XDPFG8pTErucn2pb3fKE9JEndUth25_bVJyg
Content-Type: application/json

{
        "firstName": "Yuval",
        "lastName": "Levi",
        "gender": "female",
        "userName": "yuv92",
        "birthday": "07.11.92",
        "pictureUrl": "pic1",
        "shoulder": "80",
        "chest": "80",
        "basin": "80",
        "waist": "80",
        "foot": "80",
        "height": "80",
        "weight": "80",
        "bodyType": "1",
        "status": false,
        "similarProfileId": [],
        "followers": [],
        "trackers": [],
        "notifications": [],
        "wishlist": [],
        "myPostsListId": []
}

###
GET http://localhost:4000/profile/622dc115e2a3eccfccaf0451
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NjYwNjUxMywiZXhwIjoxNjQ2NjkyOTEzfQ.67bV2VOjfg-p-bLSB3Qef4eXXUPy6ZNulRWuzsJjzfk

###
PATCH  http://localhost:4000/profile/6227ccdcb1504d4d6fac7c3b/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0Njc3NTQ5NiwiZXhwIjoxNjQ2ODYxODk2fQ.sK13D27tQgJ5Llrwc6kowWbN-Cfw9xE4I3K32w1R7Ig
Content-Type: application/json

{
        "firstName": "Yuval",
        "lastName": "Levi",
        "gender": "female",
        "userName": "yuv92",
        "birthday": "07.11.92",
        "pictureUrl": "pic1",
        "shoulder": "80",
        "chest": "80",
        "basin": "80",
        "waist": "80",
        "foot": "80",
        "height": "80",
        "weight": "80",
        "bodyType": "1",
        "status": true,
        "similarProfileId": [],
        "followers": [],
        "trackers": [],
        "notifications": [],
        "wishlist": [],
        "myPostsListId": []
}

###
DELETE   http://localhost:4000/profile/6227ccdcb1504d4d6fac7c3b/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0Njc3NTQ5NiwiZXhwIjoxNjQ2ODYxODk2fQ.sK13D27tQgJ5Llrwc6kowWbN-Cfw9xE4I3K32w1R7Ig

//****************************************Category****************************************

###
GET http://localhost:4000/category/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzM3NzE4MywiZXhwIjoxNjQ3NDYzNTgzfQ.UF6lJEKURZrs4LQp24d0pB6iFC7GgxZl5csVu6NIGD0

###
GET http://localhost:4000/category/6230fb4ae68fb223cdc6d5f3
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzM3NzE4MywiZXhwIjoxNjQ3NDYzNTgzfQ.UF6lJEKURZrs4LQp24d0pB6iFC7GgxZl5csVu6NIGD0

###
Post http://localhost:4000/category/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzUwMjQ1ZmU4M2VmMGI1MjlkZTU1NCIsImlhdCI6MTY0NzY0NDk4MSwiZXhwIjoxNjQ3NzMxMzgxfQ.xYNnRVqjGg5dmS3pNYOav7IdSNKcVxTtYEvtA5G3Woo
Content-Type: application/json

{
        "name": "Pants",
        "pictureUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8L_1DoXQIel6wBXpSZvLAaVv1Mplo5ttu6A&usqp=CAU",
        "menSubCategory": [],
        "womenSubCategory":[]
}


###
PATCH  http://localhost:4000/category/6230fb4ae68fb223cdc6d5f3/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzM3NzE4MywiZXhwIjoxNjQ3NDYzNTgzfQ.UF6lJEKURZrs4LQp24d0pB6iFC7GgxZl5csVu6NIGD0
Content-Type: application/json

{
        "name": "Edit category name",
        "menSubCategory": [],
        "womenSubCategory":[]
}


###
DELETE  http://localhost:4000/category/6227ddc2d2656fdee2ef6f04/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0Njc3NTQ5NiwiZXhwIjoxNjQ2ODYxODk2fQ.sK13D27tQgJ5Llrwc6kowWbN-Cfw9xE4I3K32w1R7Ig


//****************************************SubCategory****************************************

###
GET http://localhost:4000/subcategory/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzUwMjQ1ZmU4M2VmMGI1MjlkZTU1NCIsImlhdCI6MTY0NzY1Mzg4OSwiZXhwIjoxNjQ3NzQwMjg5fQ.gnYb1HtyZZRbdr45Z4_ooP0FrX-ck_YCkZ-Nr-LwBrI

### // By SubCategoryId
GET http://localhost:4000/subcategory/623657d250b57eb161511982
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzM5NDkyMywiZXhwIjoxNjQ3NDgxMzIzfQ.M8DdN4S0zMw84aOHGbxoLYdvxhWMP0Qgw7l_j-LDj-o

###
GET http://localhost:4000/subCategory/623657d250b57eb161511982/Male/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzUwMjQ1ZmU4M2VmMGI1MjlkZTU1NCIsImlhdCI6MTY0NzczMjA0NCwiZXhwIjoxNjQ3ODE4NDQ0fQ.L7ViHN5dYZQohLvInio1co6H7aHq_f6Qrk8OHrbv-HU

###
Post http://localhost:4000/subcategory/623657d250b57eb161511982
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjBkYTRhNDgxODMxNDZlZDdmOGUzMCIsImlhdCI6MTY0NzcxNTA5NSwiZXhwIjoxNjQ3ODAxNDk1fQ.MRx3Jf_CDfz57I3aAcG8d40822CTyWfk4vRESMIZU84
Content-Type: application/json

{
        "name": "Summer shirts",
        "pictureUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6niBNcUfbA8p6YOz6NWy8fXe5KkupgFwXGg&usqp=CAU"
}

###
PATCH  http://localhost:4000/subcategory/6227e66aff08c3354c905af6/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0Njc3NTQ5NiwiZXhwIjoxNjQ2ODYxODk2fQ.sK13D27tQgJ5Llrwc6kowWbN-Cfw9xE4I3K32w1R7Ig
Content-Type: application/json

{
        "name": "Edit SubCategory name",        
        "pictureUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8L_1DoXQIel6wBXpSZvLAaVv1Mplo5ttu6A&usqp=CAU"

}

###
DELETE  http://localhost:4000/subcategory/6227e66aff08c3354c905af6/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0Njc3NTQ5NiwiZXhwIjoxNjQ2ODYxODk2fQ.sK13D27tQgJ5Llrwc6kowWbN-Cfw9xE4I3K32w1R7Ig

//****************************************Comment****************************************

###
GET http://localhost:4000/comment/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA

### //byPostID
GET http://localhost:4000/comment/622a6ec75afdc688ae7036f3/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA

### //byCommentID
GET http://localhost:4000/comment/byId/622c45b92fae64167198bbec/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA

### //byPostID
Post http://localhost:4000/comment/622a6ec75afdc688ae7036f3
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA
Content-Type: application/json

{
        "date" : "11/03/2022",
        "text" : "Add new comment 2"
}

###
PATCH  http://localhost:4000/comment/622c2dd2118c77073a01f862/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA
Content-Type: application/json

{
        "date": "edited date",
        "text": "edited text"
}

###
DELETE  http://localhost:4000/comment/622c3a5fdb82d5c2f9a945b7/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA

//****************************************Notification****************************************

###
GET http://localhost:4000/notification/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA

### //By profoileId
GET http://localhost:4000/notification/6227d5852a70347987d0113c/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA

### // by NotificationId
GET http://localhost:4000/notification/byId/622c5c04abb2e3c8928f4910/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA

### //By profoileId
Post http://localhost:4000/notification/6227d5852a70347987d0113c
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA
Content-Type: application/json

{
        "notificationType" : "Like",
        "date" : "12/03/2022"
}

### //by notificationID
PATCH  http://localhost:4000/notification/622c5c04abb2e3c8928f4910/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA
Content-Type: application/json

{
        "notificationType" : "Comment",
        "date" : "12/03/2022"
}

### 
DELETE  http://localhost:4000/notification/622c616a33383e291b68d86b/
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjFlMTMyOGM2NjE3YWVjOTI3YWZiMyIsImlhdCI6MTY0NzA2MjI0OCwiZXhwIjoxNjQ3MTQ4NjQ4fQ.6qHiuJkcX8EBuPxiyAv3c9hOu-2r_nCnIID1zp6zfSA
